name: token_manager_grpc
description: gRPC interceptor for token injection, refresh, and retry.
version: 0.1.0
repository: https://github.com/4akloon/dart_token_manager
homepage: https://github.com/4akloon/dart_token_manager
issue_tracker: https://github.com/4akloon/dart_token_manager/issues

environment:
  sdk: ^3.7.0

dependencies:
  grpc: ">=3.2.0 <6.0.0"
  token_manager: ^0.1.0

  async: ">=2.11.0 <3.0.0"
